{ pkgs, ... }:

{
  environment.systemPackages = with pkgs; [
    lm_sensors
  ];

  # Aquacomputer Octo kernel driver
  boot.kernelModules = [ "aquacomputer_d5next" ];

  # fancontrol service for CPU temperature-based fan curves
  # The /etc/fancontrol config is generated by the setup script
  # (run `sudo fancontrol-setup` after first boot to auto-detect hwmon devices)
  services.fancontrol.enable = true;

  # The install script from hyprpunk auto-detects k10temp + octo hwmon paths
  # and writes /etc/fancontrol with these fan curves:
  #
  #   Case fans (1-6): 40C -> 15% | 60C -> 50% | 80C -> 100%
  #   CPU fans  (7-8): 45C -> 15% | 61.5C -> 54% | 78C -> 100%
  #
  # Since hwmon numbering can change across boots, the setup script
  # must be re-run if devices are re-enumerated. NixOS fancontrol
  # service reads /etc/fancontrol at startup.
  #
  # To set up: copy the fancontrol-setup script from this repo and run:
  #   sudo bash scripts/fancontrol-setup
}
