## name: ayu-dark
## Ayu Dark theme colors for kitty
foreground              #bfbdb6
background              #0b0e14
selection_foreground    #0b0e14
selection_background    #bfbdb6
cursor                  #e6b450
cursor_text_color       #000000
active_tab_foreground   #0b0e14
active_tab_background   #bfbdb6
inactive_tab_foreground #bfbdb6
inactive_tab_background #0b0e14

# black
color0  #01060e
color8  #686868

# red
color1  #ea6c73
color9  #f07178

# green
color2  #91b362
color10 #aad94c

# yellow
color3  #f9af4f
color11 #ffb454

# blue
color4  #53bdfa
color12 #59c2ff

# magenta
color5  #cda1fa
color13 #d2a6ff

# cyan
color6  #90e1c6
color14 #95e6cb

# white
color7  #c7c7c7
color15 #ffffff
